name: team_project1
description: A new Flutter project.
publish_to: 'none'
version: 0.1.0

environment:
  sdk: '>=3.0.2 <4.0.0'



dependencies:
  flutter:
    sdk: flutter

  cloud_firestore: ^4.8.0
  path: ^1.8.3
  firebase_core: ^2.13.1
  firebase_auth: ^4.6.2
  firebase_storage: ^11.2.2
  file_picker: ^5.3.2
  uuid: ^3.0.7
  google_maps_flutter: ^2.4.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^2.0.0



flutter:
  uses-material-design: true

  assets:
    - Assets/Images/
